apiVersion: apps/v1
kind: Deployment
metadata:
  name: bh-audit
  namespace: bh-audit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bh-audit
  template:
    metadata:
      labels:
        app: bh-audit
    spec:
      containers:
        - name: bh-audit
          image: bh-audit:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: postgres-audit
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: bhaudit
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: audit-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: audit-db-secret
                  key: password
       