-- AlterTable
ALTER TABLE `usuarios` ADD COLUMN `telefono` VARCHAR(191) NULL,
    MODIFY `estado` ENUM('PENDIENTE_VERIFICACION', 'PENDIENTE_APROBACION', 'ACTIVO', 'SUSPENDIDO', 'RECHAZADO') NOT NULL DEFAULT 'PENDIENTE_VERIFICACION';
